server:
  port: 8020
spring:
  application:
    name: smtp-microservice
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"
