server:
  port: ${SERVER_PORT}
spring:
  application:
    name: smtp-microservice
  datasource:
    url: ${DB_URL_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"

smtp-server:
  user: ${USER_SMTP}
  host: ${HOST_SMTP}
  ssl: ${SSL_SMTP}
  tls: ${TLS_SMTP}
  port: ${PORT_SMTP}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: SMTP microservice for SMTP BACKEND
