server:
  port: 8020
spring:
  application:
    name: smtp-microservice
  datasource:
    url: ${DB_URL_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"

smtp-server:
  user: ${USER_SMTP}
  host: ${HOST_SMTP}
  ssl: ${SSL_SMTP}
  tls: ${TLS_SMTP}
  port: ${PORT_SMTP}
