spring:
  application:
    name: email-microservice
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:smtp_db}
    username: ${DB_USER:developer}
    password: ${DB_PASSWORD:developer}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "${EUREKA_SERVER_URL}"
smtp-server:
  user: ${USER_SMTP}
  host: ${HOST_SMTP}
  ssl: ${SSL_SMTP},
  tls: ${TLS_SMTP},
  port: ${PORT_SMTP}

user-default:
  name: ${NAME_DEFAULT}
  lastName: ${LAST_NAME_DEFAULT}
  email: ${EMAIL_DEFAULT}
  password: ${PASSWORD_DEFAULT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:changemeuser}
  secret-key: ${MINIO_SECRET_KEY:changemepass}
  bucket-name: ${MINIO_BUCKET_NAME:fake-smtp}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"




